CREATE DATABASE IF NOT EXISTS studentt_management;
USE studentt_management;
CREATE TABLE IF NOT EXISTS student (
id INT AUTO_INCREMENT PRIMARY KEY,
student_name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
student_mumber VARCHAR(50) NOT NULL UNIQUE,
year_of_study INT NOT NULL,
batch_name VARCHAR(50) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);